name: My First Pipeline #name 

on: push #trigger

jobs:
  output-message: 
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code    # - denotes item in list
        uses: actions/checkout@v5

      - name: Print a message
        run: echo "🎉 My first pipeline is running!"
